const data = {
    cherkaska: {
      images: './media/cities/cherkaska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Chercasy/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-cherkasy-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Chercasy`,
    },
    chernihivska: {
      images: './media/cities/chernihivska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Chernigiv/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/desna-river-near-chernigov-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Chernigiv`,
    },
    chernivecka: {
      images: './media/cities/chernivecka.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Chernivtsi/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/novodnestrovsk-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Chernivtsi`,
    },
    dnipropetrovska: {
      images: './media/cities/dnipropetrovska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Dnipropetrovsk/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-dnepropetrovsk-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Dnipropetrovsk`,
    },
    donetska: {
      images: './media/cities/donetska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Donetsk/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/donetsk-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Donetsk`,
    },
    frankivska: {
      images: './media/cities/frankivska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Ivanofrankivsk/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/mukachevo-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Ivanofrankivsk`,
    },
    kharkivska: {
      images: './media/cities/kharkivska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Kharkiv/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/pechenezhskoe-vodohranilichshe-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Kharkiv`,
    },
    khersonska: {
      images: './media/cities/khersonska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Kherson/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kherson-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Kherson`,
    },
    khmelnitska: {
      images: './media/cities/khmelnitska.jpeg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Khmelnytskyi/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/hmelnitskiiy-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Khmelnytskyi`,
    },
    kiivska: {
      images: './media/cities/kyiv.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Kyiv/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Kyiv`,
    },
    kirovogradska: {
      images: './media/cities/kirovogradska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Kirovohrad/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/kropivnitskiiy-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Kirovohrad`,
    },
    luganskaya: {
      images: './media/cities/luganskaya.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Luhansk/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/donetsk-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Luhansk`,
    },
    lvivska: {
      images: './media/cities/lvivska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Lviv/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnestrovskiiy-kanon-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Lviv`,
    },
    mykolaivskaya: {
      images: './media/cities/mykolaivskaya.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Mikolaiv/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/nikolaev-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Mikolaiv`,
    },
    odeska: {
      images: './media/cities/odeska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Odesa/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/odessa-odeska-oblast-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Odesa`,
    },
    poltavska: {
      images: './media/cities/poltavska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Poltava/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/poltava-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Poltava`,
    },
    rivnenska: {
      images: './media/cities/rivnenska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Rivne/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/hmelnitskiiy-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Rivne`,
    },
    symska: {
      images: './media/cities/symska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Sumy/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/sumy-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Sumy`,
    },
    ternopilska: {
      images: './media/cities/ternopilska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Ternopil/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnestrovskiiy-kanon-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Ternopil`,
    },
    vinnitska: {
      images: './media/cities/vinnitska.jpeg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Vinnitsa/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/vinnitsa-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Vinnitsa`,
    },
    volunska: {
      images: './media/cities/volunska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Lutsk/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/lake-svitiaz-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Lutsk`,
    },
    zakarpatska: {
      images: './media/cities/zakarpatska.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Uzhgorod/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/uzhgorod-ukraine-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Uzhgorod`,
    },
    zaporizka: {
      images: './media/cities/zaporizka.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Zaporizhzhia/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-zaporozhye-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Zaporizhzhia`,
    },
    zhytomirska: {
      images: './media/cities/zhytomirska.jpeg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Zhytomyr/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/teterev-river-near-zhitomir-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Zhytomyr`,
    },
    khotianivka: {
      images: './media/cities/khotianivka.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Khotyanivka-kyivska/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Khotyanivka-kyivska`,
    },
    bobritsa: {
      images: './media/cities/bobritsa.jpg',
      wickliPressure: `https://www.meteoprog.ua/ua/weather/Bobrytsya-kyivska/6_10/`,
      watherTemp: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
      skyNow: `https://www.meteoprog.ua/ua/weather/Bobrytsya-kyivska`,
    },
  };
  
  export default data;
  